<expr> ::= <and>
<and> ::= .and <hist12> <hist34>
<hist12> ::= .and <hist1> <hist2>
<hist34> ::= .and <hist3> <hist4>
<hist1> ::= .historically <expr_final> <p1> <psoma>
<hist2> ::= .historically <expr_final> <p2> <psoma>
<hist3> ::= .historically <expr_final> <p3> <psoma>
<hist4> ::= .historically <expr_final> <p4> <psoma>
<p1> ::= <n0>
<p2> ::= <n8> <n6> <n4> <n3> 
<p3> ::= <n1> <n7> <n2> <n8> <n6>
<p4> ::= <n2> <n5> <n9> <n2> <n9>
<psoma> ::= <n8> <n6> <n4> <n3> 
<n0> ::= 0
<n1> ::= 1
<n2> ::= 2
<n3> ::= 3
<n4> ::= 4
<n5> ::= 5
<n6> ::= 6
<n7> ::= 7
<n8> ::= 8
<n9> ::= 9
<expr_final> ::= <and_final> | <prop>
<and_final> ::= .and <expr_final> <expr_final>
<prop> ::= .prop <num_var> <comp> <num>
<comp> ::= < | >
<num_var> ::= tempsolocm40cm
<num> ::= <digit> <digit> <digit>
<digit> ::= 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9